[package]
name = "openbook"
version = "0.1.0"
edition = "2021"

[dependencies]
num_enum = "0.7.3"
bytemuck = { version = "^1.7.2", features = ["derive", "min_const_generics"] }
static_assertions = "1.1"

