use core::fmt::Display;

pub enum OpenBookError {
    SomeError,

    InvalidInputNameLength,
    InvalidInputMarketExpired,
    InvalidInputMarketFees,
    InvalidInputLots,
    InvalidInputLotsSize,
    InvalidInputOrdersAmounts,
    InvalidInputCancelSize,
    InvalidInputPriceLots,
    InvalidInputPegLimit,
    InvalidInputOrderType,
    InvalidInputOrderId,
    InvalidInputHeapSlots,
    InvalidOracleTypes,
    InvalidSecondOracle,
    NoCloseMarketAdmin,
    InvalidCloseMarketAdmin,
    InvalidOpenOrdersAdmin,
    InvalidConsumeEventsAdmin,
    InvalidMarketVault,
    IndexerActiveOO,
    OraclePegInvalidOracleState,
    UnknownOracleType,
    OracleConfidence,
    OracleStale,
    OrderIdNotFound,
    EventHeapContainsElements,
    InvalidOrderPostIOC,
    InvalidOrderPostMarket,
    WouldSelfTrade,
    MarketHasExpired,
    InvalidPriceLots,
    InvalidOraclePrice,
    MarketHasNotExpired,
    NoOwnerOrDelegate,
    NoOwner,
    OpenOrdersFull,
    BookContainsElements,
    OpenOrdersOrderNotFound,
    InvalidPostAmount,
    DisabledOraclePeg,
    NonEmptyMarket,
    NonEmptyOpenOrdersPosition,
    WouldExecutePartially,
}


